name: "Build wget2 deps"

on:
  workflow_dispatch:
  push:
    paths:
      - "deps.yml"
      - "deps.sh"

jobs:
  build_wget2:
    runs-on: ubuntu-24.04
    container: ubuntu:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install prerequisites
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
          apt-get install -y --no-install-recommends  \
            autopoint \
            cmake \
            gettext \
            gperf \
            lzip \
            mingw-w64 \
            ninja-build \
            pkg-config-mingw-w64-x86-64 \
            git curl ca-certificates gnupg wget build-essential autoconf automake libtool python3 meson python3-pip python3-venv flex texinfo jq \
            retry bc lld
      - name: Compile
        env:
          CROSS_HOST: "x86_64-w64-mingw32"
        run: |
          chmod +x "${GITHUB_WORKSPACE}/deps.sh"
          "${GITHUB_WORKSPACE}/deps.sh"
      - name: Archive wget2.exe
        uses: actions/upload-artifact@v4
        with:
          name: wget2-deps.tar.zst
          path: "wget2-deps.tar.zst"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: wget2-deps
          allowUpdates: true
          artifacts: "wget2-deps.tar.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
